[package]
name = "rust-leet-code"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "217"
path = "src/easy/217/main.rs"

[[bin]]
name = "242"
path = "src/easy/242/main.rs"

[[bin]]
name = "1"
path = "src/easy/1/main.rs"
